### ISSUE TITLE
Addon cannot be enabled

### ISSUE THREAD

**Issue by emshupisim** [MichaelGlenMontague/shape_keys_plus#13]
error message: 

```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\esuta\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\shape_keys_plus-master\__init__.py", line 4, in <module>
    from shape_keys_plus import core
ModuleNotFoundError: No module named 'shape_keys_plus'


```

**Comment by MichaelGlenMontague** [comment]
You downloded the GitHub repository directly (the "master" branch which gets downloaded as `shape_keys_plus-master`) without renaming the folder inside of the .zip file back to `shape_keys_plus`, which is the missing module. The newest version is available on the [Releases](https://github.com/MichaelGlenMontague/shape_keys_plus/releases/) page so that this extra step isn't necessary.
